(function(){'use strict';
 const R=ACReading,E=Admin.escape,box=document.getElementById('learningProgress'),content=document.getElementById('content');
 let category=new URLSearchParams(location.search).get('category')||'',focus=new URLSearchParams(location.search).get('focus')||'',activeOnly=false;
 if(!Object.hasOwn(AC_LEARNING_CATEGORIES,category))category='';
 function records(){try{return R.all();}catch(e){return [];}}
 function url(path){return new URL(path,location.href).href;}
 function sectionText(v){return v.chapter||(v.chapterIndex?'第 '+v.chapterIndex+' 個章節':'已保存閱讀位置');}
 function refresh(){const view=new URLSearchParams(location.search).get('view')||'admin',learning=view==='learning',personal=view==='personal',saved=records(),ongoing=saved.filter(v=>v.status==='reading');box.hidden=false;if(!learning&&!personal){const pending=ongoing.filter(v=>/apps\/(learning|courses)\//.test(v.path));box.hidden=!pending.length;box.innerHTML=pending.length?'<details class="ac-reading-summary"><summary>📖 '+pending.length+' 項課程進行中 · 繼續上次閱讀</summary>'+pending.slice(0,3).map(v=>'<p><a href="'+E(url(v.path))+'">'+E(v.title)+'</a><small> · '+E(sectionText(v))+'</small></p>').join('')+'<a href="?view=learning&focus=progress">查看全部閱讀紀錄</a></details>':'';return;}
  const visible=saved.filter(v=>learning?(/apps\/(learning|courses)\//.test(v.path)):v.path.startsWith('apps/personal/'));
  const progress=focus==='progress'?visible:visible.filter(v=>v.status==='reading').slice(0,6);
  const categoryTabs=learning?'<nav class="ac-course-tabs" aria-label="課程分類分頁">'+[['','全部課程'],...Object.entries(AC_LEARNING_CATEGORIES)].map(([k,v])=>'<button data-course-category="'+k+'" aria-pressed="'+(category===k)+'">'+E(v)+'</button>').join('')+'</nav>':'';const options=Object.entries(AC_LEARNING_CATEGORIES).map(([k,v])=>'<option value="'+k+'" '+(category===k?'selected':'')+'>'+E(v)+'</option>').join('');
  box.innerHTML=categoryTabs+'<div class="ac-learning-controls">'+(learning?'<label>課程分類 <select id="ac-course-category"><option value="">全部課程</option>'+options+'</select></label>':'')+'<button id="ac-reading-filter" aria-pressed="'+activeOnly+'">只看進行中</button><button id="ac-progress-all">全部閱讀紀錄</button><button id="ac-reading-export">匯出進度備份</button><button id="ac-reading-import">匯入進度</button><input id="ac-reading-file" type="file" accept=".json" hidden></div><div class="ac-reading-summary"><h2>'+E(focus==='progress'?'我的閱讀紀錄':'繼續上次閱讀')+'</h2><p>'+visible.filter(v=>v.status==='reading').length+' 項進行中 · 紀錄保存在此瀏覽器，可匯出備份帶到其他裝置。</p>'+(progress.length?progress.map(v=>'<article class="ac-progress-item"><div><strong>'+E(v.title)+'</strong><small>'+E(sectionText(v))+' · '+E(v.status==='completed'?'已完成':v.status==='paused'?'已暫停':'進行中')+'</small><small>上次閱讀 '+E(new Date(v.updated).toLocaleString())+(Date.now()-v.updated>7*864e5&&v.status==='reading'?' · 已超過 7 天，安排時間繼續吧':'')+'</small></div><a class="button primary" href="'+E(url(v.path))+'">續讀</a><button data-read-state="'+E(v.path)+'">'+(v.status==='reading'?'暫停提醒':'恢復進行中')+'</button></article>').join(''):'<p>目前沒有閱讀紀錄。開啟課程後，章節及閱讀位置會自動保存。</p>')+'</div>';
  for(const card of content.querySelectorAll('[data-tool-id]')){card.querySelector('.ac-read-card-progress')?.remove();const c=AC_CATALOG.find(c=>c.id===card.dataset.toolId)||{},v=c.links?.length?R.get(R.id(c.links[0].url)):null;card.hidden=learning&&!!category&&c.category!==category||activeOnly&&(!v||v.status!=='reading');if(v){const label=document.createElement('p');label.className='ac-read-card-progress';label.textContent=(v.status==='completed'?'✓ 已完成':'↻ '+sectionText(v))+' · '+new Date(v.updated).toLocaleDateString();card.append(label);}}
  box.querySelectorAll('[data-course-category]').forEach(button=>button.onclick=()=>{category=button.dataset.courseCategory;const u=new URL(location.href);category?u.searchParams.set('category',category):u.searchParams.delete('category');history.replaceState(null,'',u);window.AC_HOME_REFRESH();});const select=document.getElementById('ac-course-category');if(select)select.onchange=()=>{category=select.value;const u=new URL(location.href);category?u.searchParams.set('category',category):u.searchParams.delete('category');history.replaceState(null,'',u);window.AC_HOME_REFRESH();};
  document.getElementById('ac-reading-filter').onclick=()=>{activeOnly=!activeOnly;window.AC_HOME_REFRESH();};
  document.getElementById('ac-progress-all').onclick=()=>{focus=focus==='progress'?'':'progress';refresh();};
  document.getElementById('ac-reading-export').onclick=()=>Admin.download('AC_Reading_Progress_'+new Date().toISOString().slice(0,10)+'.json',{schema:'ac-reading-backup-v1',records:records()});
  const file=document.getElementById('ac-reading-file');document.getElementById('ac-reading-import').onclick=()=>file.click();
  file.onchange=async()=>{try{const f=file.files[0];if(!f)return;if(f.size>5*1024*1024)throw Error('進度檔過大');const d=JSON.parse(await f.text());if(d.schema!=='ac-reading-backup-v1'||!Array.isArray(d.records)||d.records.length>1000||!d.records.every(R.valid)||new Set(d.records.map(v=>v.path)).size!==d.records.length)throw Error('進度檔格式不正確，未匯入任何紀錄');const incoming=d.records.filter(v=>!R.get(v.path)||R.get(v.path).updated<v.updated);if(!incoming.length){Admin.toast('本機進度已是最新，沒有重複匯入。');return;}if(!confirm('將新增或更新 '+incoming.length+' 筆較新的閱讀紀錄；較新的本機紀錄會保留。是否匯入？'))return;Admin.download('AC_Reading_Before_Import.json',{schema:'ac-reading-backup-v1',records:records()});incoming.forEach(R.put);window.AC_HOME_REFRESH();Admin.toast('已合併 '+incoming.length+' 筆進度。');}catch(e){Admin.toast(e.message,true);}};
  box.querySelectorAll('[data-read-state]').forEach(b=>b.onclick=()=>{const v=R.get(b.dataset.readState);if(!v)return;v.status=v.status==='reading'?'paused':'reading';v.updated=Date.now();try{R.put(v);window.AC_HOME_REFRESH();}catch(e){Admin.toast('未能儲存：'+e.message,true);}});
 }
 const observer=new MutationObserver(refresh);observer.observe(content,{childList:true});window.addEventListener('storage',()=>{window.AC_HOME_REFRESH();});window.addEventListener('ac-reading-changed',()=>{refresh();});
 const top=document.createElement('button');top.className='ac-home-top';top.textContent='↑ 頂端';top.onclick=()=>window.scrollTo({top:0,behavior:'smooth'});document.body.append(top);refresh();
})();
