(function(){'use strict';
 const script=document.currentScript,base=new URL('../',script.src),group=script.dataset.group||'admin',code=script.dataset.zh||'zh',fn=script.dataset.langfn;
 const words={zh:['← 行政中心','回本分類','入口語言','教材／工具內容保留原有語言'],en:['← Admin Center','Back to category','Launcher language','Course / tool content keeps its original language'],km:['← មជ្ឈមណ្ឌលរដ្ឋបាល','ត្រឡប់ប្រភេទ','ភាសាច្រកចូល','មាតិកាប្រើភាសាដើម']};
 const read=()=>{try{return JSON.parse(localStorage.getItem('ac_admin_lang'))||'zh'}catch(e){return 'zh'}};
 function init(){if(document.getElementById('ac-module-toolbar'))return;const el=document.createElement('nav');el.id='ac-module-toolbar';el.setAttribute('aria-label','Admin Center navigation');document.body.prepend(el);const css=document.createElement('link');css.rel='stylesheet';css.href=new URL('shared/module-shell.css',base).href;document.head.append(css);const full=document.querySelector('#app')||document.querySelector('.app');if(full&&['poetry_map.html','supermarket_inventory.html'].some(n=>location.pathname.endsWith(n))){const fit=()=>{full.style.height='calc(100dvh - '+el.getBoundingClientRect().height+'px)'};new ResizeObserver(fit).observe(el);fit();}
 const chapterNav=group==='learning'&&document.querySelector('nav#TOC,nav#nav,nav.toc');
 if(chapterNav){const drawer=document.createElement('details'),summary=document.createElement('summary');drawer.className='ac-chapter-drawer';summary.textContent='章節目錄 / Chapters';chapterNav.before(drawer);drawer.append(summary,chapterNav);drawer.open=!matchMedia('(max-width:640px)').matches;chapterNav.addEventListener('click',event=>{if(event.target.closest('a')&&matchMedia('(max-width:640px)').matches)drawer.open=false;});}
 function draw(){const lang=read(),w=words[lang]||words.zh;el.replaceChildren();for(const [label,url] of [[w[0],new URL('index.html?view=admin',base)],[w[1],new URL('index.html?view='+group,base)]]){const a=document.createElement('a');a.textContent=label;a.href=url.href;el.append(a)}const span=document.createElement('span');span.textContent=document.title;el.append(span);const select=document.createElement('select');select.setAttribute('aria-label',w[2]);for(const [v,l] of [['zh','繁中'],['en','EN'],['km','ខ្មែរ']])select.add(new Option(l,v));select.value=lang;select.onchange=()=>{try{localStorage.setItem('ac_admin_lang',JSON.stringify(select.value));if(fn&&typeof window[fn]==='function')window[fn](select.value==='zh'?code:select.value);draw()}catch(e){alert(e.message)}};el.append(select);if(!fn){const note=document.createElement('small');note.className='ac-course-note';note.textContent=w[3];el.append(note)}}draw();
 if(fn&&typeof window[fn]==='function'){try{window[fn](read()==='zh'?code:read())}catch(e){/* Keep native controls if a module has not completed initialization. */}}
 }if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
